version: '2'
services:
    data:
        build: ./data
        volumes:
            - .:/app
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - proxy=
        depends_on:
            - data
        volumes_from:
            - data
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - data
            - php-fpm
        volumes_from:
            - data
        links:
            - php-fpm